//
//  ProjectExporter+Text.swift
//  CinePlanner
//
//  The plain-text export: a readable scene-and-shot breakdown.
//
//  Split out of ProjectExporter.swift, which had grown past 2,900 lines with
//  four unrelated export formats in it. Same type, same behaviour — an extension
//  in its own file, so each format can be read on its own.
//

import Foundation
import SwiftUI
import PDFKit
import AVFoundation
import UniformTypeIdentifiers
import os

extension ProjectExporter {
    // MARK: - Text Generation

    func generateFullTextContent() -> String {
        Log.export.debug("🔵 [CONTENT] Starting content generation...")

        let rule = String(repeating: "=", count: 80)
        let formatter = DateFormatter()
        formatter.dateStyle = .long
        formatter.timeStyle = .short

        let orderedScenes = exportScenes.sorted { $0.sortOrder < $1.sortOrder }
        let totalShots = orderedScenes.reduce(0) { $0 + $1.shots.count }

        var output = ""

        // ── Header ──────────────────────────────────────────────────────────
        output += rule + "\n"
        output += "\(project.filmName.uppercased()) — SHOT LIST\n"
        if !textContextLine.isEmpty {
            output += textContextLine + "\n"
        }
        for (label, value) in [("Production Company", project.productionCompany),
                               ("Director", project.director),
                               ("Cinematographer", project.cinematographer)] {
            let v = value.trimmingCharacters(in: .whitespacesAndNewlines)
            if !v.isEmpty { output += "\(label): \(v)\n" }
        }
        output += "Exported \(formatter.string(from: Date()))\n"
        output += rule + "\n\n"

        // ── Contents (only worth it for longer lists) ───────────────────────
        if orderedScenes.count > 1 {
            output += "CONTENTS\n"
            for scene in orderedScenes {
                let label = "\(scene.sceneNumber)\(scene.suffix)"
                let count = scene.shots.count
                let countText = "\(count) shot\(count == 1 ? "" : "s")"
                output += "  " + padRight(label, 6) + padRight(sceneSlug(scene), 48) + countText + "\n"
            }
            output += "\n"
        }

        // ── Statistics ──────────────────────────────────────────────────────
        let stats = calculateStatistics()
        output += "STATISTICS\n"
        output += "  " + padRight("Shots with photos", 22) + "\(stats.shotsWithPhotos) / \(totalShots)\n"
        output += "  " + padRight("Shots with coverage", 22) + "\(stats.shotsWithCoverage) / \(totalShots)\n"
        output += "  " + padRight("Complete (both)", 22) + "\(stats.completeShots) / \(totalShots)  (\(stats.completionPercentage)%)\n"
        output += "  " + padRight("Scene types", 22)
        output += "INT/DAY \(stats.intDayCount) · INT/NIGHT \(stats.intNightCount) · EXT/DAY \(stats.extDayCount) · EXT/NIGHT \(stats.extNightCount)\n"
        let hasScript = (version?.pdfData ?? project.scriptPDFData) != nil
        output += "  " + padRight("Script PDF", 22) + (hasScript ? "Attached" : "None") + "\n"
        output += "\n"

        // ── Scene breakdown ─────────────────────────────────────────────────
        output += generateExportText(orderedScenes: orderedScenes)

        // ── Footer ──────────────────────────────────────────────────────────
        output += "\n" + rule + "\n"
        output += "End of shot list · generated by CinePlanner\n"
        output += rule + "\n"

        Log.export.debug("✅ [CONTENT] Content generation complete!")
        return output
    }

    /// "Episode 2 · Version 3 · 14 scenes · 42 shots" — mirrors the export
    /// window's context line, minus the film name (already the title above).
    private var textContextLine: String {
        var parts: [String] = []
        if project.isSeries, let episode = version?.episode?.title { parts.append(episode) }
        if let versionName = version?.name { parts.append(versionName) }
        let sceneCount = exportScenes.count
        let shotCount = exportScenes.reduce(0) { $0 + $1.shots.count }
        parts.append("\(sceneCount) scene\(sceneCount == 1 ? "" : "s")")
        parts.append("\(shotCount) shot\(shotCount == 1 ? "" : "s")")
        return parts.joined(separator: " · ")
    }

    /// Screenplay-style slugline: "EXT. COTTON FIELD – DAY".
    private func sceneSlug(_ scene: Scene) -> String {
        let intExt = scene.isInterior ? "INT." : "EXT."
        let time = scene.isDay ? "DAY" : "NIGHT"
        let place = scene.nickname.trimmingCharacters(in: .whitespacesAndNewlines)
        if place.isEmpty {
            return "\(intExt) – \(time)"
        }
        return "\(intExt) \(place.uppercased()) – \(time)"
    }

    /// Pads `s` with trailing spaces to `width`; never truncates.
    private func padRight(_ s: String, _ width: Int) -> String {
        s.count >= width ? s + " " : s + String(repeating: " ", count: width - s.count)
    }
    
    // Calculate project statistics
    private func calculateStatistics() -> (
        shotsWithPhotos: Int,
        shotsWithCoverage: Int,
        completeShots: Int,
        completionPercentage: Int,
        intDayCount: Int,
        intNightCount: Int,
        extDayCount: Int,
        extNightCount: Int
    ) {
        var shotsWithPhotos = 0
        var shotsWithCoverage = 0
        var completeShots = 0
        var intDayCount = 0
        var intNightCount = 0
        var extDayCount = 0
        var extNightCount = 0
        
        let totalShots = exportScenes.reduce(0) { $0 + $1.shots.count }
        
        for scene in exportScenes {
            // Count scene types
            if scene.isInterior && scene.isDay { intDayCount += 1 }
            else if scene.isInterior && !scene.isDay { intNightCount += 1 }
            else if !scene.isInterior && scene.isDay { extDayCount += 1 }
            else if !scene.isInterior && !scene.isDay { extNightCount += 1 }
            
            for shot in scene.shots {
                // Check for photos
                if shot.hasAnyReferenceMedia {
                    shotsWithPhotos += 1
                }
                
                // Check for coverage
                if let selections = shot.scriptCoverageSelections, !selections.isEmpty {
                    shotsWithCoverage += 1
                }
                
                // Check if complete (has both photos and coverage)
                if shot.hasAnyReferenceMedia &&
                   shot.scriptCoverageSelections != nil &&
                   !(shot.scriptCoverageSelections?.isEmpty ?? true) {
                    completeShots += 1
                }
            }
        }
        
        let completionPercentage = totalShots > 0 ? Int(Double(completeShots) / Double(totalShots) * 100) : 0
        
        return (
            shotsWithPhotos: shotsWithPhotos,
            shotsWithCoverage: shotsWithCoverage,
            completeShots: completeShots,
            completionPercentage: completionPercentage,
            intDayCount: intDayCount,
            intNightCount: intNightCount,
            extDayCount: extDayCount,
            extNightCount: extNightCount
        )
    }
    
    private func generateExportText(orderedScenes: [Scene]) -> String {
        Log.export.debug("🔵 [EXPORT_TEXT] Starting scene breakdown...")

        // Aligns detail values into a column; survives proportional fonts far
        // better than the old box-drawing frame did.
        let sceneRule = String(repeating: "─", count: 72)
        let valueIndent = "      "                       // under "  SHOT"
        let contIndent = valueIndent + String(repeating: " ", count: 12)
        func detailRow(_ label: String, _ value: String) -> String {
            valueIndent + padRight(label, 12) + value + "\n"
        }

        var output = ""

        for scene in orderedScenes {
            let shotCount = scene.shots.count
            let countText = "\(shotCount) shot\(shotCount == 1 ? "" : "s")"

            var header = "SCENE \(scene.sceneNumber)\(scene.suffix) — \(sceneSlug(scene))"
            if scene.scriptPageNumber > 0 {
                header += "  (p.\(scene.scriptPageNumber))"
            }
            header += " · \(countText)"

            output += sceneRule + "\n"
            output += header + "\n"
            output += sceneRule + "\n\n"

            let orderedShots = scene.shots.sorted { $0.shotNumber < $1.shotNumber }
            if orderedShots.isEmpty {
                output += "  (No shots in this scene)\n\n"
                continue
            }

            for shot in orderedShots {
                var line = "  SHOT \(shot.displayNumber)"
                if !shot.nickname.isEmpty {
                    line += " — \(shot.nickname)"
                }
                output += line + "\n"

                if shot.hasSize {
                    var sizeText = shot.sizeShort
                    if shot.hasSecondSize {
                        sizeText += " → " + shot.secondSizeShort
                    }
                    output += detailRow("Size", sizeText)
                }

                if shot.hasType {
                    var typeText = shot.typeShort
                    if shot.hasSecondType {
                        typeText += " + " + shot.secondTypeShort
                    }
                    if shot.hasThirdType {
                        typeText += " + " + shot.thirdTypeShort
                    }
                    output += detailRow("Type", typeText)
                }

                if shot.lensfocal > 0 {
                    let focal = shot.lensIsPrime
                        ? "\(shot.lensfocal)mm"
                        : "\(shot.lensfocal)→\(shot.lensfocalEnd)mm"
                    output += detailRow("Focal", focal)
                }

                if shot.hasGrip {
                    output += detailRow("Grip", shot.gripName)
                }
                if !shot.camera.isEmpty {
                    output += detailRow("Camera", shot.camera)
                }
                if !shot.framelines.isEmpty {
                    output += detailRow("Framelines", shot.framelines)
                }
                if !shot.lensPreset.isEmpty {
                    output += detailRow("Lens", shot.lensPreset)
                }
                if !shot.extraInfo.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                    output += detailRow("Extra", shot.extraInfo)
                }

                // Reference media — noted as present (text can't carry it).
                if let media = referenceSummary(for: shot) {
                    output += detailRow("Reference", media)
                }

                // Script coverage
                if let selections = shot.scriptCoverageSelections, !selections.isEmpty {
                    output += detailRow("Coverage", "\(selections.count) selection\(selections.count == 1 ? "" : "s")")
                    for selection in selections {
                        output += contIndent + "· " + formatCoverageSummary(selection) + "\n"
                    }
                }

                output += "\n"
            }
        }

        Log.export.debug("✅ [EXPORT_TEXT] Scene breakdown complete!")
        return output
    }

    /// "2 photos · 1 video · 1 map", or nil when the shot has no media.
    private func referenceSummary(for shot: Shot) -> String? {
        let photos = shot.referenceImages.count
        let maps = shot.referenceMaps.count
        let videos = shot.orderedReferences.filter { $0.videoExtension != nil }.count

        var parts: [String] = []
        if photos > 0 { parts.append("\(photos) photo\(photos == 1 ? "" : "s")") }
        if videos > 0 { parts.append("\(videos) video\(videos == 1 ? "" : "s")") }
        if maps > 0 { parts.append("\(maps) map\(maps == 1 ? "" : "s")") }
        return parts.isEmpty ? nil : parts.joined(separator: " · ")
    }
}
